from agent.prompts import (
    HELPDESK_SYSTEM_PROMPT,
    INTENT_CLASSIFICATION_PROMPT,
    RESPONSE_GENERATION_PROMPT,
    ESCALATION_PROMPT,
    GENERAL_RESPONSE_PROMPT,
)

__all__ = [
    "HELPDESK_SYSTEM_PROMPT",
    "INTENT_CLASSIFICATION_PROMPT",
    "RESPONSE_GENERATION_PROMPT",
    "ESCALATION_PROMPT",
    "GENERAL_RESPONSE_PROMPT",
]
